[General]

# --- PATHS ---
Background="/usr/share/sddm/themes/r4chi-sddm/bloq.png"
UserIcon="~/.face.icon"

Font="Terminus"
FontSize="12"

# --- COLORS ---
MainColor="#0A0708"
PanelColor="#0A0708"
AccentColor="#F5582D"
TextColor="#cbe2e6"
InputColor="#0A0708"
InputTextColor="#cbe2e6"

InputBorderColor="#243083" 

# --- LOGIN BUTTON ---
ButtonColor="#F5582D"
ButtonTextColor="#0A0708"

CornerRadius="0"
RoundCorners="0"
InputCornerRadius="0"
ButtonCornerRadius="0"

BorderWidth="1"
BorderColor="#243083"

# --- PANEL STYLING ---
PanelOpacity="1.0"