# oxh-hyprland-dotfiles by occhi
[General]

# --- PATHS ---
Background="/usr/share/backgrounds/y8yxlx.jpg"
UserIcon="~/.face.icon"

Font="Terminus"
FontSize="12"

# --- COLORS ---
MainColor="#0C0B05"
PanelColor="#0C0B05"
AccentColor="#C4C700"
TextColor="#FEFEFE"
InputColor="#0C0B05"
InputTextColor="#FEFEFE"

InputBorderColor="#21252e" 

# --- LOGIN BUTTON ---
ButtonColor="#C4C700"
ButtonTextColor="#000000"

CornerRadius="0"
RoundCorners="0"
InputCornerRadius="0"
ButtonCornerRadius="0"

BorderWidth="1"
BorderColor="#21252e"

# --- PANEL STYLING ---
PanelOpacity="1.0"