# Adachi Rei - Webcore/Black Theme
theme[main_bg]="#0B0B0B"
theme[main_fg]="#EFEFEF"
theme[title]="#EFEFEF"
theme[hi_fg]="#F6592E"
theme[selected_bg]="#0D2E8F"
theme[selected_fg]="#EFEFEF"
theme[inactive_fg]="#96969A"
theme[graph_text]="#96969A"
theme[meter_bg]="#101010"
theme[proc_misc]="#96969A"

theme[cpu_box]="#101010"
theme[mem_box]="#101010"
theme[net_box]="#101010"
theme[proc_box]="#101010"
theme[div_line]="#96969A"

# Temperaturas
theme[temp_start]="#0D2E8F"
theme[temp_mid]="#D58304"
theme[temp_end]="#F6592E"

# CPU (Azul/Naranja)
theme[cpu_start]="#0D2E8F"
theme[cpu_mid]="#A0D3D9"
theme[cpu_end]="#F6592E"

# RAM (Gris calido/dorado)
theme[free_start]="#96969A"
theme[free_mid]="#7A3A00"
theme[free_end]="#7A3A00"
theme[cached_start]="#A0D3D9"
theme[cached_mid]="#A0D3D9"
theme[cached_end]="#A0D3D9"
theme[available_start]="#EFEFEF"
theme[available_mid]="#EFEFEF"
theme[available_end]="#EFEFEF"
theme[used_start]="#B34700"
theme[used_mid]="#F6592E"
theme[used_end]="#F27405"

# Red
theme[download_start]="#0D2E8F"
theme[download_mid]="#A0D3D9"
theme[download_end]="#A0D3D9"
theme[upload_start]="#B34700"
theme[upload_mid]="#F6592E"
theme[upload_end]="#F6592E"

# Procesos
theme[process_start]="#0D2E8F"
theme[process_mid]="#A0D3D9"
theme[process_end]="#F6592E"
